url: https://github.com/kubernetes-sigs/cluster-api-operator/releases/download/v0.18.1/cluster-api-operator-0.18.1.tgz
version: 0.18.1
# cluster-api-operator is only used as a dependency of rancher-turtles
doNotRelease: true
